// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6349.RoboChiefs;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainSpeedController3;
    public static SpeedController drivetrainSpeedController2;
    public static SpeedController drivetrainSpeedController1;
    public static SpeedController drivetrainSpeedController0;
    public static RobotDrive drivetrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainSpeedController3 = new Spark(3);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 3", (Spark) drivetrainSpeedController3);
        
        drivetrainSpeedController2 = new Spark(2);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 2", (Spark) drivetrainSpeedController2);
        
        drivetrainSpeedController1 = new Spark(1);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 1", (Spark) drivetrainSpeedController1);
        
        drivetrainSpeedController0 = new Spark(0);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 0", (Spark) drivetrainSpeedController0);
        
        drivetrainRobotDrive41 = new RobotDrive(drivetrainSpeedController2, drivetrainSpeedController3,
              drivetrainSpeedController1, drivetrainSpeedController0);
        
        drivetrainRobotDrive41.setSafetyEnabled(true);
        drivetrainRobotDrive41.setExpiration(0.1);
        drivetrainRobotDrive41.setSensitivity(0.5);
        drivetrainRobotDrive41.setMaxOutput(1.0);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
